### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by dionyziz** [yann2192/pyelliptic#24]
In [OpenBazaar](https://github.com/OpenBazaar/OpenBazaar) we use [the MIT license](https://blog.openbazaar.org/openbazaar-is-now-mit-licensed/), and we also [use pyelliptic](https://github.com/OpenBazaar/OpenBazaar/blob/master/requirements.txt#L10). However, I believe this use may be incompatible with our licenses.

Would you please give us your opinion on how you think we should solve this licensing incompatibility?

As pyelliptic is a library, would it be reasonable to ask to switch to the LGPL so that it can be used as an external library in projects such as OpenBazaar?

Thank you very much!

**Comment by yann2192** [comment]
@Kagami thanks, I'll fix that.
