### ISSUE TITLE
bin_to_b58check not working as expected

### ISSUE THREAD

**Issue by vdsm** [yann2192/pyelliptic#30]
The following reproduces: `bin_to_b58check(hash_160('a'))`. I'm not sure where exactly it's going wrong but I can't understand the intention of the decode function with respect to the `while` loop. I had go at fixing it and decided to "fail fast"! Cheers

**Comment by yann2192** [comment]
I'm not the author of arithmetic.py. See https://github.com/yann2192/pyelliptic/pull/21.

@appleorange1 any idea ?

**Comment by appleorange1** [comment]
No, sorry. I'm not the author either.

@Atheros1 should hopefully be able to fix this :)
