### ISSUE TITLE
Add more convenient way of generating pubkeys for various curves

### ISSUE THREAD

**Issue by rand-func** [yann2192/pyelliptic#36]
Public keys of elliptic curves are made by addition/multiplication of private points. For generating public key, each curve needs a lot of parameters: prime P, base points Gx and Gy, coefficient a, coefficient b, order and seed. 

By default, pyelliptic provides no means to convert private keys to public keys. In *arithmetic.py*, which is used in PyBitMessage, there is a method called "privtopub(privkey)", but parameters for multiplication are hardcoded only for secp256k1 curve, which makes most cool functions of *arithmetic.py* useless for other curves. 

UPD: When you generate a key pair, you get a key pair of privkey, pubkeyX and pubkeyY. If you discard public key parameters, there are no means to get them back in pyelliptic. In any case, here is a code from PyBitmessage that can generate pubkeys back: 

    def point_multiplication(secret, curve_name):
        k = OpenSSL.EC_KEY_new_by_curve_name(OpenSSL.get_curve(curve_name))
        priv_key = OpenSSL.BN_bin2bn(secret, 32, None)
        group = OpenSSL.EC_KEY_get0_group(k)
        pub_key = OpenSSL.EC_POINT_new(group)
             
        OpenSSL.EC_POINT_mul(group, pub_key, priv_key, None, None, None)
        OpenSSL.EC_KEY_set_private_key(k, priv_key)
        OpenSSL.EC_KEY_set_public_key(k, pub_key)

        size = OpenSSL.i2o_ECPublicKey(k, None)
        mb = OpenSSL.create_string_buffer(size)
        OpenSSL.i2o_ECPublicKey(k, OpenSSL.byref(OpenSSL.pointer(mb)))

        OpenSSL.EC_POINT_free(pub_key)
        OpenSSL.BN_free(priv_key)
        OpenSSL.EC_KEY_free(k)
        return mb.raw

... so I'm closing the issue.

**Comment by locksmithone** [comment]
If it is the secp256k1 curve, shouldn't there be a parameter B = 7?

http://www.secg.org/sec2-v2.pdf
