### ISSUE TITLE
ECC Point Compression

### ISSUE THREAD

**Issue by ankitpopli1891** [yann2192/pyelliptic#39]
Currently the [`get_pubkey`](https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/ecc.py#L116) and [`get_privkey`](https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/ecc.py#L128) method returns public key and private key that is not compatible with other libraries like [SpongyCastle](https://github.com/rtyley/spongycastle) and [Cryptopp](https://github.com/mmoss/cryptopp).

As per the standards, we should use [Point Compression or Compact Point Representation](https://tools.ietf.org/html/draft-jivsov-ecc-compact-05).

**Comment by fredigato** [comment]
:+1:  I think the standard is not applied in the point encoding/decoding. The first octect should be the point conversion form used, not the curve ID, uncompressed form should be prefered, no point length needed in compression form. This way of encoding the pubkey and points makes this library shrinks it's interoperability to 0.

**Comment by yann2192** [comment]
Hi,

I'm agree with you. But right now I don't have the time to rewrite this part.

However, if you have the courage, I accept contributions ;)

**Comment by fredigato** [comment]
Hi!

I am working on it, I already have support for 'hex' and 'binary' input and output pubkeys in a more standard (only uncompressed) way and the computed secret is now just the X asis of the shared point.

I still need to fix the encrypt and decrypt I broke in the way (ECDH is working and tested against node crypto).

**Comment by ankitpopli1891** [comment]
:+1: I did start this myself but found a quicker workaround for my use case. 

Looking forward to it. 
Thanks

**Comment by fredigato** [comment]
PR created :) #40

**Comment by yann2192** [comment]
@fredigato Thanks for the PR :). I'll take a look when I'll have some free time.

**Comment by yann2192** [comment]
@ankitpopli1891 @fredigato The PR is merged. I'll publish the version 1.5.7 on pypi today.

**Comment by arjan-s** [comment]
Please put up a warning on the README that this is a backwards incompatible change!
My application broke horribly after updating pyelliptic to 1.5.7, and probably so will (some) others!

**Comment by yann2192** [comment]
Sorry for the inconvenience, I pushed the warning on the README.
