### ISSUE TITLE
Decrypting with ECC should not require public key

### ISSUE THREAD

**Issue by ccampbell** [yann2192/pyelliptic#42]
I don't know if this used to work or not, but I have noticed that when using ECC to decrypt it requires you to pass in the public key in addition to the private key when creating the object. I believe only the private key should be required.

It fails with

```
Traceback (most recent call last):
  File "/Users/craig/Dropbox/codestuff/encryptr.py", line 221, in <module>
    result = new_ecc.decrypt(ciphertext)
  File "/usr/local/lib/python3.4/site-packages/pyelliptic/ecc.py", line 535, in decrypt
    raise RuntimeError("Fail to verify data")
RuntimeError: Fail to verify data
```

Reproduce code:

``` python
import pyelliptic

ecc = pyelliptic.ECC(curve='prime256v1')
public_key = ecc.get_pubkey()
private_key = ecc.get_privkey()
plaintext = 'abc'
ciphertext = ecc.encrypt(plaintext, public_key)

# this works fine
new_ecc = pyelliptic.ECC(privkey=private_key, pubkey=public_key, curve='prime256v1')
result = new_ecc.decrypt(ciphertext)

# this raises exception
new_ecc = pyelliptic.ECC(privkey=private_key, curve='prime256v1')
result = new_ecc.decrypt(ciphertext)
```

**Comment by thethythy** [comment]
Hi,

Encrypt and decrypt use ECDH method. With ECDH, Alice and Bob must have our own private key.
See https://en.wikipedia.org/wiki/Elliptic_curve_Diffie%E2%80%93Hellman for example.

**Comment by ccampbell** [comment]
@thethythy thanks for the reply. I think I may just be confused since I don't know much about cryptography. 

I'm not talking about the private key. It is my understanding that in order to decrypt you shouldn't have to pass in the public key also. 

I also was looking at this which I'm not sure is related:

http://stackoverflow.com/questions/12480776/how-do-i-obtain-the-public-key-from-an-ecdsa-private-key-in-openssl

**Comment by mouse07410** [comment]
ECC encryption, as pointed out above, must be done via Key Exchange (such as ECDH or EC El Gamal).

 **Encryption** needs **sender's private** key *and* **recipient's public key**. 

 **Decryption** is the other way - it requires **sender's public key** *and* **recipient's private key**. 

Usually the sender's public key is passed along as a part of the encrypted message (because usually it i ephemeral - generated just for this encryption and used only once).

Hope this helps.

**Comment by ccampbell** [comment]
@mouse07410 @thethythy thanks for your replies. I was digging into this again, and while I understand what you are saying, and it is correct, I don't think code in this library is handling it correctly.

If you look here https://github.com/yann2192/pyelliptic/blob/b9e9ae5ae0884ca817d834e24606e690bb6d2820/pyelliptic/ecc.py#L515 the `pubkey` variable is included along with the ciphertext. That *is* the **sender's public key** which as you said is passed along with the encrypted message. I think the second code sample I sent in the original ticket here should still work since you have the **sender's public key** as well as the **recipient's private key** which should be all that is required to decrypt:

```python
# this raises exception
new_ecc = pyelliptic.ECC(privkey=private_key, curve='prime256v1')
result = new_ecc.decrypt(ciphertext)
```

--

Upon looking further at the code in this library, I think something else is looks fishy. With ECIES (from what I understand from reading about it) the shared secret (ECDH) should be derived from the **sender's private key** and **recipient's public key**, but in the code it looks like it is derived from two public keys. Take a look at https://github.com/yann2192/pyelliptic/blob/b9e9ae5ae0884ca817d834e24606e690bb6d2820/pyelliptic/ecc.py#L270.

I hope I am missing something here since I am not an encryption expert and reading code can be difficult, but when looking at other code examples in other languages for ECIES they usually create an ephemeral key before encrypting and use the private key from that along with the public key of the recipient. I do not see that happening here.

For example you can see in this go implementation https://github.com/obscuren/ecies/blob/7c0f4a9b18d992166452d8cd32caaefd92b26386/ecies.go#L227-L233 that a new key is generated `R` and on line 233 it computes the shared secret using that along with the recipient's public key.

Hopefully this is just a misunderstanding.

**Comment by thethythy** [comment]
The ECDH key is computed line 311: 
```ecdh_keylen = OpenSSL.ECDH_compute_key(ecdh_keybuffer, 32, other_pub_key, own_key, 0)```
where:
```other_pub_key``` is the recipient's public key (set lines 277-299)
```own_key``` is the sender's private key (set lines 301-308)

For encryption see lines 509-510:
```ephem = ECC(curve=ephemcurve)```
==> get an ephemeral EC key pair (it generates a key pair on the fly)

```key = sha512(ephem.raw_get_ecdh_key(pubkey_x, pubkey_y)).digest()```
==> get ECDH with ephemeral sender's private key (```ephem``` variable ) and recipient's public key (```pubkey_x, pubkey_y```)

For decryption see line 532:
```key = sha512(self.raw_get_ecdh_key(pubkey_x, pubkey_y)).digest()```
==> here ```self``` is a EC that already contains the private key and we set public key with ```pubkey_x, pubkey_y```
