### ISSUE TITLE
Exception: Couldn't load OpenSSL lib...

### ISSUE THREAD

**Issue by fatmaSaeid** [yann2192/pyelliptic#44]
Traceback (most recent call last):
  File "C:/Users/Maryam/PycharmProjects/bachproject/test.py", line 9, in <module>
    import pyelliptic
  File "build\bdist.win32\egg\pyelliptic__init__.py", line 14, in <module>
  File "build\bdist.win32\egg\pyelliptic\openssl.py", line 342, in <module>
Exception: Couldn't load OpenSSL lib ...

I'm still new to this module and this error arises when I use the commented example shown in the ecc.py file.
Are there any dependencies that I should download other than the openssl module? (I also have the pycrypto module I don't know if it's related or not)

**Comment by rand-func** [comment]
@fatmaSaeid You must install OpenSSL library - it is a pyelliptic's dependency.
On Windows, you can use installer provided here: http://slproweb.com/products/Win32OpenSSL.html

**Comment by fatmaSaeid** [comment]
@rand-func I have it already downloaded. I dont know what else can be the problem?
![image](https://cloud.githubusercontent.com/assets/13191436/16851272/18eed0de-4a03-11e6-9183-7ab86fe8b079.png)

**Comment by rand-func** [comment]
@fatmaSaeid Seems like You got pyOpenSSL, and the thing is, pyelliptic uses just OpenSSL, a library written in C/C++. You can see it in line 525 here: https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/openssl.py#L525

To fix it, literally search the web, find and download file libeay32.dll Then just drop it in pyelliptic folder. It will work.
