### ISSUE TITLE
Python3.4 issue

### ISSUE THREAD

**Issue by sureshvv** [yann2192/pyelliptic#49]
File "/home/s/webapps/appt/lib/python3.4/site-packages/pyelliptic/ecc.py", line 89, in **init**
    self.privkey, self.pubkey_x, self.pubkey_y = self._generate()
  File "/home/s/webapps/appt/lib/python3.4/site-packages/pyelliptic/ecc.py", line 223, in _generate
    raise Exception("[OpenSSL] EC_KEY_generate_key FAIL ... " + OpenSSL.get_error())
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by naveensinghal** [comment]
I am getting kind of same exception for Python2.7. Don't think this to be python issue.
(Ref Issue Link: https://github.com/yann2192/pyelliptic/issues/48)

**Comment by sureshvv** [comment]
May be OpenSSL.get_error() returns bytes.

**Comment by naveensinghal** [comment]
How is this method called from your python code ?
