### ISSUE TITLE
Add support OpenSSL 1.1

### ISSUE THREAD

**Issue by stalkerg** [yann2192/pyelliptic#50]
Subj. Currently you can't import pyelliptic with openssl 1.1 and greater. Also pyelliptic not understand LD_LIBRARY_\* env for change lookup folder.

**Comment by yann2192** [comment]
Hi,

I don't have the time or the motivation to correct properly pyelliptic. 

Moreover, this method (using ctypes) to use OpenSSL isn't stable. I'll make a last release removing the ECDH/ECDSA part but keeping Cipher and Hash stuffs and tag pyelliptic as deprecated.

I suggest to looking at pyOpenSSL, cryptography, pySodium, curve25519, etc ...

Regards.

**Comment by stalkerg** [comment]
Thanks for the answer. Ah... I should be porting some libs from PyElliptic now.

**Comment by ofek** [comment]
@stalkerg Definitely use https://github.com/pyca/cryptography

**Comment by friedcell** [comment]
Wondering why the solution wasn't "update readme to make clear pyelliptic will only ever work on OpenSSL 1.0.x and tag as deprecated". My issue is that pyelliptic was the only library I could get to compile on a RaspberryPI A+/B+ properly.
