### ISSUE TITLE
no encryption possible if curve is defined on too small field

### ISSUE THREAD

**Issue by erazortt** [yann2192/pyelliptic#6]
Encryption is not possible with curves on fields smaller or equal than 224bits.
Can be circumvented by:

--- pyelliptic-1.5/pyelliptic/ecc.py    2012-12-10 22:47:00.000000000 +0100
+++ pyelliptic-1.5_mychanges/pyelliptic/ecc.py  2013-06-23 14:31:01.353120820 +0200
@@ -227,8 +227,8 @@
             ecdh_keylen = OpenSSL.ECDH_compute_key(
                 ecdh_keybuffer, 32, other_pub_key, own_key, 0)
-            if ecdh_keylen != 32:
-                raise Exception("[OpenSSL] ECDH keylen FAIL ...")
-            # if ecdh_keylen != 32:
-            #     raise Exception("[OpenSSL] ECDH keylen FAIL ...")

But I am not sure if this is a good idea to drop the exception..

**Comment by thethythy** [comment]
Hi every body,

In fact I think the point is that, in the method raw_get_ecdh_key, you don't take care of the curve
to compute the ECDH shared key (you assume this key size is alway <= 32 bytes).

The ECDH shared key size depend of the curve used. For example do the following code:

field_size = OpenSSL.EC_GROUP_get_degree(OpenSSL.EC_KEY_get0_group(own_key))
secret_len = int((field_size + 7) / 8)
ecdh_keybuffer = OpenSSL.malloc(0, secret_len)
OpenSSL.ECDH_set_method(own_key, OpenSSL.ECDH_OpenSSL())
ecdh_keylen = OpenSSL.ECDH_compute_key(ecdh_keybuffer, secret_len, other_pub_key, own_key, 0)

if ecdh_keylen != secret_len:
      raise Exception("[OpenSSL] ECDH keylen FAIL ... " + OpenSSL.get_error())

Best regards
